version: '3.7'

services:
    buid-app:
      image: shridh0r/erpnext:develop
      build:
        context: .
        dockerfile: ./Dockerfile

    web-app:
        image: shridh0r/erpnext:develop
        ports:
            - "8005:8000"
        restart: unless-stopped
        volumes:
          - ./sites:/home/frappe/frappe-bench/sites
          - ./sites/Procfile:/home/frappe/frappe-bench/Procfile
          - ./run.sh:/home/frappe/frappe-bench/run.sh
            # - ./sites/assets/frappe/:/home/frappe/frappe-bench/apps/frappe/frappe/public/
        depends_on:
          - redis
          - db
        env_file:
         - env_file

        # command: sh -c "cd /home/frappe/frappe-bench && bench use site1.local && /home/frappe/.local/bin/bench start"
        # command: sh -c "cd /home/frappe/frappe-bench/sites && /home/frappe/frappe-bench/env/bin/gunicorn -b 0.0.0.0:8000 --workers 8 --threads 4 -t 120 frappe.app:application --preload"
        command: sh run.sh

    default-worker:
        image: shridh0r/erpnext:develop
        restart: unless-stopped
        volumes:
          - ./sites:/home/frappe/frappe-bench/sites
          - ./sites/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
        command: sh -c "cd /home/frappe/frappe-bench && /home/frappe/.local/bin/bench worker --queue default"
        depends_on:
          - web-app

    long-worker:
        image: shridh0r/erpnext:develop
        restart: unless-stopped
        volumes:
          - ./sites:/home/frappe/frappe-bench/sites
          - ./sites/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
        command: sh -c "cd /home/frappe/frappe-bench && /home/frappe/.local/bin/bench worker --queue long"
        depends_on:
          - web-app

    short-worker:
        image: shridh0r/erpnext:develop
        restart: unless-stopped
        volumes:
          - ./sites:/home/frappe/frappe-bench/sites
          - ./sites/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
        command: sh -c "cd /home/frappe/frappe-bench && /home/frappe/.local/bin/bench worker --queue short"
        depends_on:
          - web-app

    scheduler:
        image: shridh0r/erpnext:develop
        restart: unless-stopped
        volumes:
          - ./sites:/home/frappe/frappe-bench/sites
          - ./sites/common_site_config.json:/home/frappe/frappe-bench/sites/common_site_config.json
        command: sh -c "cd /home/frappe/frappe-bench && /home/frappe/.local/bin/bench schedule"
        depends_on:
          - web-app

    socketio:
        image: shridh0r/erpnext:develop
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
          - ./sites:/home/frappe/frappe-bench/sites
        command: sh -c "cd /home/frappe/frappe-bench && /usr/bin/node /home/frappe/frappe-bench/apps/frappe/socketio.js"
        depends_on:
          - web-app

    redis:
        image: "redis:5.0.5-alpine"
        ports:
          - 6379
        volumes:
          - ./data/redis:/data

    # db:
    #     image: "postgres"
    #     ports:
    #       - 5432
    #     volumes:
    #       - ./data/postgres:/var/lib/postgresql/data

    db:
        image: "wangxian/alpine-mysql"
        ports:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
        volumes:
          - ./data/mysql:/app
          - ./my.cnf:/etc/mysql/my.cnf

    nginx:
        image: nginx
        ports:
          - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - ./sites/assets:/home/assets
        depends_on:
          - web-app